# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestEditarPropiedad():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editarPropiedad(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1936, 1056)
    WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.LINK_TEXT, "Registro"))
        )
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "username").send_keys("angelneria_19")
    self.driver.find_element(By.ID, "password").send_keys("pepe")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-custom").click()
    element = WebDriverWait(self.driver, 10).until(
    EC.presence_of_element_located((By.CSS_SELECTOR, ".bg-transparent"))
)
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element.click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Gestión de propiedades").click()
    self.driver.find_element(By.LINK_TEXT, "Editar").click()
    self.driver.find_element(By.ID, "id_titulo").click()
    self.driver.find_element(By.ID, "id_titulo").send_keys("Prueba2")
    self.driver.find_element(By.ID, "id_descripcion").click()
    self.driver.find_element(By.ID, "id_descripcion").send_keys("prueba2")
    self.driver.find_element(By.ID, "id_ubicacion").click()
    self.driver.find_element(By.ID, "id_ubicacion").send_keys("prueba2")
    self.driver.find_element(By.CSS_SELECTOR, ".tab-content").click()
    self.driver.find_element(By.ID, "id_num_maximo_huespedes").send_keys("2")
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.ID, "id_num_maximo_habitaciones").send_keys("3")
    self.driver.find_element(By.CSS_SELECTOR, ".footer-button").click()
  
