# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestReservarPropiedad():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reservarPropiedad(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1936, 1056)
    WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.LINK_TEXT, "Registro"))
        )
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) .card-img-top").click()
    self.driver.execute_script("arguments[0].click();", self.driver.find_element(By.CSS_SELECTOR, ".btn-warning"))

    

    nombre_input = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.ID, "id_nombre_usuario_anonimo"))
    )
    self.driver.execute_script("arguments[0].scrollIntoView(true);", nombre_input)
    self.driver.execute_script("arguments[0].click();", nombre_input)  # Hacer clic vía JavaScript
    nombre_input.send_keys("manu")

    self.driver.find_element(By.ID, "id_correo_usuario_anonimo").click()
    self.driver.find_element(By.ID, "id_correo_usuario_anonimo").send_keys("manu@gmail.com")
    self.driver.find_element(By.ID, "id_telefono_usuario_anonimo").click()
    self.driver.find_element(By.ID, "id_telefono_usuario_anonimo").send_keys("11234567788")
    self.driver.find_element(By.ID, "id_numero_huespedes").click()
    self.driver.find_element(By.ID, "id_numero_huespedes").send_keys("4")
    self.driver.find_element(By.ID, "fechas_escogidas").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-next-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-next-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-next-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-next-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-next-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-day:nth-child(28)").click()
    self.driver.find_element(By.ID, "fechas_escogidas").send_keys("2025-04-26")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    iframe = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.TAG_NAME, "iframe"))
        )
    self.driver.switch_to.frame(iframe)

    # Ahora, esperamos que el campo "cardnumber" esté disponible dentro del iframe
    cardnumber_input = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.NAME, "cardnumber"))
        )
    cardnumber_input.send_keys("4242 4242 4242 4242")
        
        # Rellenamos el resto de los campos de pago
    self.driver.find_element(By.NAME, "exp-date").send_keys("04 / 26")
    self.driver.find_element(By.NAME, "cvc").send_keys("666")
    self.driver.find_element(By.NAME, "postal").send_keys("66666")
        
        # Regresamos al contenido principal de la página
    self.driver.switch_to.default_content()
        
        # Hacemos clic en el botón para finalizar la reserva
    self.driver.find_element(By.ID, "submit-button").click()
        
  
