# Generated by Django 5.1.1 on 2024-11-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("ubicacion", models.CharField(max_length=255)),
                (
                    "precio_por_noche",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "anfitrion"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.perfilusuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "inquilino"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.perfilusuario",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alquileres.propiedad",
                    ),
                ),
            ],
        ),
    ]
