# Generated by Django 5.1.3 on 2024-11-14 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='disponible',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='disponible_fecha_final',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='disponible_fecha_inicio',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
