# Generated by Django 5.1.3 on 2024-11-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0004_remove_propiedad_disponible_fecha_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='num_maximo_habitaciones',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='num_maximo_huespedes',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='servicios_disponibles',
            field=models.TextField(default='Es un valor por defecto'),
            preserve_default=False,
        ),
    ]
