# Generated by Django 5.1.3 on 2024-11-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0005_propiedad_num_maximo_habitaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
    ]
