# Generated by Django 5.1.3 on 2024-11-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alquileres", "0007_propiedadesdeseadas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_fin",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_inicio",
        ),
        migrations.AddField(
            model_name="reserva",
            name="fechas_reserva",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="reserva",
            name="numero_huespedes",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
