# Generated by Django 5.1.3 on 2024-11-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alquileres",
            "0008_remove_reserva_fecha_fin_remove_reserva_fecha_inicio_and_more",
        ),
        ("usuarios", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="email_cliente",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="nombre_cliente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="telefono_cliente",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="inquilino",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo_usuario": "inquilino"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.perfilusuario",
            ),
        ),
    ]
