# Generated by Django 5.1.3 on 2024-11-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "alquileres",
            "0010_rename_email_cliente_reserva_correo_usuario_anonimo_and_more",
        ),
        ("usuarios", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calificacion", models.PositiveSmallIntegerField()),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="alquileres.propiedad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="usuarios.perfilusuario",
                    ),
                ),
            ],
            options={
                "unique_together": {("propiedad", "usuario")},
            },
        ),
    ]
