# Generated by Django 5.1.3 on 2024-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alquileres", "0011_valoracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("apartamento", "Apartamento"),
                    ("casa", "Casa"),
                    ("habitacion", "Habitación"),
                    ("villa", "Villa"),
                    ("estudio", "Estudio"),
                    ("loft", "Loft"),
                    ("bungalow", "Bungalow"),
                    ("cabaña", "Cabaña"),
                    ("castillo", "Castillo"),
                    ("caravana", "Caravana"),
                    ("barco", "Barco"),
                    ("iglú", "Iglú"),
                    ("finca", "Finca"),
                    ("chalet", "Chalet"),
                    ("casa_rural", "Casa Rural"),
                    ("residencia_universitaria", "Residencia Universitaria"),
                    ("penthouse", "Penthouse"),
                    ("granja", "Granja"),
                    ("hostal", "Hostal"),
                    ("hotel", "Hotel"),
                    ("camping", "Camping"),
                    ("resort", "Resort"),
                    ("tienda_de_campaña", "Tienda de Campaña"),
                    ("casa_flotante", "Casa Flotante"),
                    ("casa_en_arbol", "Casa en Árbol"),
                    ("domo", "Domo"),
                    ("yurta", "Yurta"),
                    ("container", "Container"),
                    ("apartamento_estudio", "Apartamento Estudio"),
                    ("aparthotel", "Aparthotel"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
