name: Dependabot Alert Report

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Dependabot alerts
        id: dependabot-alerts
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPENDABOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts" > dependabot-alerts.json

      - name: Mostrar dependabot-alerts.json
        run: cat dependabot-alerts.json

      - name: Format alerts for DefectDojo
        run: |
          # Creación de un formato compatible con DefectDojo
          jq '[.[] | {
            "title": .security_advisory.summary,
            "description": .security_advisory.description,
            "severity": .security_advisory.severity,
            "package": {
              "name": .dependency.package.name,
              "ecosystem": .dependency.package.ecosystem
            },
            "affected_version": .dependency.manifest_path,
            "fixed_version": .security_advisory.patched_versions,
            "reference": .security_advisory.references[0].url,
            "cvss": .security_advisory.cvss.score
          }]' dependabot-alerts.json > formatted-dependabot-alerts.json

      - name: Create GitHub issue with Dependabot alerts
        run: |
          echo "## Dependabot Security Alert Report" > dependabot-summary.md
          jq -r '.[] | "- **Package**: \(.package.name) (\(.package.ecosystem))\n  - **Title**: \(.title)\n  - **Severity**: \(.severity)\n  - **Affected Version**: \(.affected_version)\n  - **Fixed Version**: \(.fixed_version)\n  - **Description**: \(.description)\n  - [Reference](\(.reference))\n"' formatted-dependabot-alerts.json >> dependabot-summary.md

      - name: Create GitHub issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Dependabot Vulnerability Report"
          content-filepath: dependabot-summary.md
          labels: security, dependency, vulnerability

      - name: Import Dependabot report to DefectDojo
        run: |
          curl -X POST "https://1107-80-31-44-98.ngrok-free.app/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
          -H "Content-Type: multipart/form-data" \
          -F "product_name=PAI4" \
          -F "engagement_name=Pruebas de vulnerabilidades con sonarcloud, trivy y dependabot" \
          -F "scan_type=Generic Findings Import" \
          -F "file=@formatted-dependabot-alerts.json" \
          -F "close_old_findings=True"