name: DevSecOps Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd escapadas_a_tu_medida
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          cd escapadas_a_tu_medida
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          cd escapadas_a_tu_medida
          python manage.py test

      - name: Install OpenJDK 17 explicitly
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo update-alternatives --config java
          java -version

      - name: Set JAVA_HOME and SONAR_SCANNER_HOME
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export SONAR_SCANNER_HOME=/opt/sonar-scanner
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "SONAR_SCANNER_HOME=$SONAR_SCANNER_HOME" >> $GITHUB_ENV
          java -version
          sonar-scanner -v

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: escapadas_a_tu_medida
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
